# Quiz Questions

### 1. How do you import the panda package in Python?

In [26]:
import pandas as pd

### 2. What function do you use to read a CSV file in pandas?

In [30]:
df = pd.read_csv("/Users/suchipatel/Downloads/Students Social Media Addiction 2.csv")

In [31]:
print(df.head())

   Student_ID  Age  Gender Academic_Level     Country  Avg_Daily_Usage_Hours  \
0           1   19  Female  Undergraduate  Bangladesh                    5.2
1           2   22    Male       Graduate       India                    2.1
2           3   20  Female  Undergraduate         USA                    6.0
3           4   18    Male    High School          UK                    3.0
4           5   21    Male       Graduate      Canada                    4.5

  Most_Used_Platform Affects_Academic_Performance  Sleep_Hours_Per_Night  \
0          Instagram                          Yes                    6.5
1            Twitter                           No                    7.5
2             TikTok                          Yes                    5.0
3            YouTube                           No                    7.0
4           Facebook                          Yes                    6.0

   Mental_Health_Score Relationship_Status  Conflicts_Over_Social_Media  \
0                    6     In Relationship                            3
1                    8              Single                            0
2                    5         Complicated                            4
3                    7              Single                            1
4                    6     In Relationship                            2

   Addicted_Score
0               8
1               3
2               9
3               4
4               7

### 3. How do you display the first 5 rows of a DataFrame in pandas?

In [32]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

### 4. How do you calculate the mean of a column named Age in a DataFrame named df?

In [33]:
df["Age"].mean()

np.float64(20.659574468085108)

### 5. How do you calculate the median of a column named Student ID in a DataFrame named df?

In [42]:
df["Student_ID"].median()

np.float64(353.0)

### 6. How do you calculate the standard deviation of a column named Score in a DataFrame named df?

In [44]:
df["Avg_Daily_Usage_Hours"].std()

np.float64(1.257394521073143)

### 7. How do you find the number of missing values in each column of a DataFrame named df?

In [45]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64

### 8. How do you calculate the correlation between two columns, Age and Gender, in a DataFrame named df?

In [47]:
df["Age"].corr(df["Student_ID"])

np.float64(0.22230602065908858)

### 9. How do you select a subset of a DataFrame df where the column Age is greater than 30?

In [48]:
df[df["Age"] > 30]

Empty DataFrame
Columns: [Student_ID, Age, Gender, Academic_Level, Country, Avg_Daily_Usage_Hours, Most_Used_Platform, Affects_Academic_Performance, Sleep_Hours_Per_Night, Mental_Health_Score, Relationship_Status, Conflicts_Over_Social_Media, Addicted_Score]
Index: []

### 10. How do you calculate the range (maximum - minimum) of a column named Mental Health Score in a DataFrame named df?

In [50]:
df["Mental_Health_Score"].max() - df["Mental_Health_Score"].min()

np.int64(5)

### 11. How do you group a DataFrame df by a column named Avg Daily Usage Hours and calculate the mean of Sleep Hours Per Night within each group?

In [51]:
df.groupby("Avg_Daily_Usage_Hours")["Sleep_Hours_Per_Night"].mean()

Avg_Daily_Usage_Hours
1.5    8.000
2.0    7.800
2.1    7.500
2.2    8.500
2.3    8.425
       ...
8.1    4.200
8.2    4.100
8.3    4.000
8.4    3.900
8.5    3.800
Name: Sleep_Hours_Per_Night, Length: 67, dtype: float64

### 12. How do you group a DataFrame df by two columns, Academic Level and Country, and count the number of rows within each group?

In [54]:
df.groupby(["Academic_Level", "Country"]).size()

Academic_Level  Country
Graduate        Afghanistan     1
                Bahamas         1
                Bahrain         1
                Bangladesh      4
                Belarus         1
                               ..
Undergraduate   Ukraine         1
                Uruguay         1
                Vatican City    1
                Vietnam         1
                Yemen           1
Length: 139, dtype: int64

### 13. How do you use the groupby method to find the maximum Age in each Mental Health Score in a DataFrame df?

In [55]:
df.groupby("Age")["Mental_Health_Score"].max()

Age
18    7
19    8
20    8
21    8
22    8
23    9
24    8
Name: Mental_Health_Score, dtype: int64

### 14. How do you create a cross-tabulation table that shows the frequency count of Academic Level (rows) and Country (columns) in a DataFrame df?

In [56]:
pd.crosstab(df["Academic_Level"], df["Country"])

Country,Afghanistan,Albania,Andorra,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bahrain,...,UAE,UK,USA,Ukraine,Uruguay,Uzbekistan,Vatican City,Venezuela,Vietnam,Yemen
Academic_Level,,,,,,,,,,,,,,,,,,,,,
Graduate,1,0,0,0,0,0,0,0,1,1,...,0,16,5,0,0,0,0,1,0,0
High School,0,0,1,1,1,0,0,0,0,0,...,1,1,0,0,0,1,0,0,0,0
Undergraduate,0,1,0,0,0,14,1,1,0,0,...,7,5,35,1,1,0,1,0,1,1

### 15. How do you create a cross-tabulation table that shows the mean Country for each combination of Academic Level (rows) and Salary (columns) in a DataFrame df?

In [67]:
pd.crosstab(
    df["Academic_Level"],
    df["Country"],
    values=df["Age"],
    aggfunc="mean"
)

Country,Afghanistan,Albania,Andorra,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bahrain,...,UAE,UK,USA,Ukraine,Uruguay,Uzbekistan,Vatican City,Venezuela,Vietnam,Yemen
Academic_Level,,,,,,,,,,,,,,,,,,,,,
Graduate,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,22.0,...,NaN,21.3125,23.2,NaN,NaN,NaN,NaN,22.0,NaN,NaN
High School,NaN,NaN,19.0,18.0,18.0,NaN,NaN,NaN,NaN,NaN,...,19.000000,18.0000,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN
Undergraduate,NaN,19.0,NaN,NaN,NaN,19.928571,19.0,19.0,NaN,NaN,...,19.571429,20.6000,19.4,19.0,21.0,NaN,20.0,NaN,21.0,20.0